{% set name = "pymcubes" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a72476a22a4c98907acec0c5ef8d46f4451fa987c7efeaf970990775826ed8b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython
    - numpy
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - scipy >=1.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mcubes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmneila/PyMCubes
  summary: Marching cubes for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - willGraham01
    - pmneila
