{% set name = "pymcubes" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMCubes-{{ version }}.tar.gz
  sha256: ad25e96f5a32fb5a363372005a4b68eaf03025c1e781ada62e73b10b45ff7cbb

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython
    - numpy
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - scipy >=1.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mcubes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmneila/PyMCubes
  summary: Marching cubes for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - willGraham01
    - pmneila
